---
- hosts: ubuntu
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install required packages
      apt:
        name: "{{ required_packages }}"
        state: present

    - name: Create AppDynamics Directory
      file:
        path: "{{ appdynamics_dir }}" 
        state: directory
        mode: "0755"

    - name: Create Machine Agent Directory
      file:
        path: "{{ machine_agent_directory }}"
        state: directory
        mode: "0755"

    - name: Download & decompress AppDynamics Machine Agent
      unarchive:
        src: "{{ machine_agent_source }}"
        dest: "{{ machine_agent_directory }}"
        remote_src: yes

    - name: Write controller host to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-host
        value: "{{ controller_host }}"

    - name: Write controller port to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/controller-port
        value: "{{ controller_port }}"

    - name: Write application name to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/application-name
        value: "{{ application_name }}"

    - name: Write tier name to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/tier-name
        value: "{{ tier_name }}"

    - name: Write node name to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/node-name
        value: "{{ node_name }}"

    - name: Write Server Visibility Monitoring setting to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/sim-enabled
        value: "{{ server_visibility_enabled }}"

    - name: Write account name to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-name
        value: "{{ account_name }}"

    - name: Write account access key to Machine Agent configuration file
      xml:
        path: "{{ machine_agent_directory }}/conf/controller-info.xml"
        xpath: /controller-info/account-access-key
        value: "{{ account_access_key }}"

    - name: Download & decompress AppDynamics Azure Monitor
      unarchive:
        src: "{{ azure_monitor_extension_source }}"
        dest: "{{ machine_agent_directory }}/monitors"
        remote_src: yes

    - name: Write Azure Monitor configuration
      template:
        src: "{{ azure_monitor_config_template_local }}"
        dest: "{{ machine_agent_directory }}/monitors/{{ azure_monitor_config_file }}"
        mode: "0755"

    - name: Write Extension Workbench Script
      template:
        src: "{{ extension_workbench_script_local }}"
        dest: "{{ machine_agent_directory }}/{{ extension_workbench_script }}"
        mode: "0755"

    - name: Configure Machine Agent in systemd
      copy:
        src: "{{ machine_agent_directory }}/{{ machine_agent_systemd_service_file }}" 
        dest: "/{{ machine_agent_systemd_service_file }}"
        remote_src: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Machine Agent service
      service:
        name: "{{ machine_agent_systemd_service_name }}"
        enabled: true
        state: restarted
